### ISSUE TITLE
Can't access to phpvirtualbox interface

### ISSUE THREAD

**Issue by alpha842** [NethServer/nethserver-phpvirtualbox-5.2#2]
the phpvirtualbox interface asks for login but always get the following error:

"Exception Object
(
    [message:protected] => Could not connect to host (http://localhost:18083/)
    [string:Exception:private] => 
    [code:protected] => 64
    [file:protected] => /usr/share/phpvirtualbox-5.2/endpoints/api.php
    [line:protected] => 134
    [trace:Exception:private] => Array
        (
        )

    [previous:Exception:private] => 
)"

already changed 127.0.0.1 to localhost in the config file.
also changed access to public.
its a vanilla instalation of nethserver 7.5 trough the latest iso available.

**Comment by stephdl** [comment]
hi and thank for your interest

I would bet that the kernel was not updated with the the right header, hence virtualbox is not running

`systemctl status vboxdrv`

it should output that virtualbox is running

I changed my way, now you have a new rpm to test

`yum update -y; reboot`
reboot to be sure to be on the last kernel
`yum install nethserver-virtualbox-5.2-phpvirtualbox --enablerepo=nethforge-testing -y`


You could open a thread on https://community.nethserver.org if you have some troubles

**Comment by DavidePrincipi** [comment]
If you need to file a new issue please see https://github.com/nethserver/dev
